### ISSUE TITLE
Revisar todo site da Atena

### ISSUE THREAD

**Issue by cenicoemir** [impulsoteam/atena#303]

**Comment by goldblade** [comment]
Problemas detectados 
=========

Home
------

- [ ]  Background com comportamento estranho
- [ ] Links das tabs não estão funcionando
- [ ] Textos lorem ipsum

Ranking
--------

- [x] Falta Link para "Como funciona"
- [ ] Pontuações do Ranking Mensal não estão sendo exibidos corretamente
- [ ] Ranking Geral BG do Header não ta sendo exibido

Autenticação
-------

- [x] Adicionar link para voltar a home na tela de erro
- [x] Autenticação em staging não ta funcionando corretamente, verificar url de callbacks e debuggar (Precisamos cadastrar os linkedinids na database de staging e production

**Comment by goldblade** [comment]
Baixei a base de produção local. e vi que precisa fazer o normalize do score nas interações. Temos dois cenários lembro que mudou o peso da pontuação para reações se não me engano.. temos que rodar normalize com o cenario a anterior a isso e pós isso e ai e preciso ajustar a função pegando como referência a data.
